// Shared data — the Yakushima trip
window.PACKLOG_DATA = {
  trip: {
    id: 'yak-2026',
    title: '屋久岛',
    subtitle: '徒步 · 露营',
    folio: 'FOLIO 004',
    destCity: '屋久岛',
    destCountry: 'Japan',
    destContinent: 'Asia',
    coords: '30.3466° N, 130.5020° E',
    elev: '1,935m max',
    startDate: '2026-05-08',
    endDate: '2026-05-14',
    days: 7,
    daysToGo: 21,
    scenes: ['hiking', 'camping', 'trail_run'],
    travel: ['friends'],
    status: 'packing',
    notes: '年降雨量全日本最高，硬壳冲锋衣必须，提前下载离线地图。日本A型插头。',
    weather: {
      tempLow: 14,
      tempHigh: 22,
      rain: 68,
      season: '春 · 山区',
      desc: '多雨多雾 · 早晚温差大',
    },
    progress: { packed: 18, total: 34, buy: 4, optional: 6 },
  },
  trips: [
    { id: 't1', title: '屋久岛', sub: '徒步 · 露营', days: 7, folio: '004', dateRange: 'May 8 — May 14', progress: 0.53, scene: 'hiking', status: 'packing', pinned: true },
    { id: 't2', title: '北海道', sub: '城市 · 滑雪', days: 9, folio: '003', dateRange: 'Feb 2 — Feb 10', progress: 1, scene: 'ski', status: 'reviewed' },
    { id: 't3', title: 'ABC Trek', sub: '高海拔徒步', days: 14, folio: '002', dateRange: 'Oct 12 — Oct 25', progress: 1, scene: 'hiking', status: 'done' },
    { id: 't4', title: '冰岛环岛', sub: '自驾 · 越野跑', days: 10, folio: '001', dateRange: 'Jun 4 — Jun 13', progress: 1, scene: 'drive', status: 'reviewed' },
    { id: 't5', title: '清迈', sub: '城市漫游', days: 5, folio: '—', dateRange: 'Dec 22 — Dec 26', progress: 0, scene: 'city', status: 'planning' },
  ],
  categories: [
    { id: 'docs',   n: '01', name: '证件 & 出行必备', count: 6 },
    { id: 'shoes',  n: '02', name: '鞋履',          count: 3 },
    { id: 'cloth',  n: '03', name: '衣物',          count: 9 },
    { id: 'bag',    n: '04', name: '背包 & 收纳',    count: 4 },
    { id: 'out',    n: '05', name: '户外装备',       count: 6 },
    { id: 'care',   n: '06', name: '日用 & 护理',    count: 5 },
    { id: 'tech',   n: '07', name: '数码 & 通讯',    count: 4 },
    { id: 'med',    n: '08', name: '药品 & 急救',    count: 3 },
  ],
  items: [
    { id: 'i1', cat: 'docs', name: '护照', status: 'packed', container: 'body', brand: '', note: '有效期需6个月以上', packed: true },
    { id: 'i2', cat: 'docs', name: '机票打印件', status: 'must', container: 'body', packed: false },
    { id: 'i3', cat: 'docs', name: '现金（日元）', status: 'buy', container: 'body', note: '约 ¥50,000 ≈ ¥2,400', packed: false },
    { id: 'i4', cat: 'docs', name: '信用卡 / IC卡', status: 'must', container: 'body', packed: true },
    { id: 'i5', cat: 'docs', name: '旅行保险单', status: 'must', container: 'backpack', packed: true },
    { id: 'i6', cat: 'docs', name: '国际驾照', status: 'opt', container: 'body', packed: false },

    { id: 'i7', cat: 'shoes', name: '徒步鞋', status: 'packed', container: 'wearing', brand: 'Salomon X Ultra 4 Mid GTX', note: '日本山区推荐硬壳，防水优先', packed: true },
    { id: 'i8', cat: 'shoes', name: '营地拖鞋', status: 'must', container: 'backpack', brand: 'Teva Original Universal', packed: false },
    { id: 'i9', cat: 'shoes', name: '越野跑鞋', status: 'opt', container: 'suitcase', brand: 'Hoka Speedgoat 5', packed: false },

    { id: 'i10', cat: 'cloth', name: '硬壳冲锋衣', status: 'packed', container: 'wearing', brand: 'Arc\u2019teryx Beta AR', note: '屋久岛年降雨量全日本最高，硬壳必须', packed: true },
    { id: 'i11', cat: 'cloth', name: '抓绒中间层', status: 'packed', container: 'backpack', brand: 'Patagonia R1', packed: true },
    { id: 'i12', cat: 'cloth', name: '羽绒服', status: 'must', container: 'backpack', brand: 'Montbell Plasma 1000', note: '营地保暖 · 轻量优先', packed: false },
    { id: 'i13', cat: 'cloth', name: '速干T恤 × 3', status: 'packed', container: 'suitcase', packed: true },
    { id: 'i14', cat: 'cloth', name: '长袖速干 × 2', status: 'packed', container: 'suitcase', packed: true },
    { id: 'i15', cat: 'cloth', name: '徒步长裤', status: 'packed', container: 'wearing', brand: 'Fjallraven Keb', packed: true },
    { id: 'i16', cat: 'cloth', name: '速干内裤 × 4', status: 'packed', container: 'suitcase', packed: true },
    { id: 'i17', cat: 'cloth', name: '羊毛袜 × 3', status: 'must', container: 'suitcase', brand: 'Smartwool / Darn Tough', packed: false },
    { id: 'i18', cat: 'cloth', name: '保暖帽 + 手套', status: 'opt', container: 'backpack', packed: false },

    { id: 'i19', cat: 'bag', name: '托运行李箱', status: 'packed', container: 'suitcase', brand: 'Rimowa Essential 65L', packed: true },
    { id: 'i20', cat: 'bag', name: '登山背包 40L', status: 'packed', container: 'wearing', brand: 'Osprey Talon 44', packed: true },
    { id: 'i21', cat: 'bag', name: '防水袋 × 3', status: 'must', container: 'backpack', note: '电子产品 + 衣物分装', packed: false },
    { id: 'i22', cat: 'bag', name: '压缩袋', status: 'opt', container: 'suitcase', packed: false },

    { id: 'i23', cat: 'out', name: '帐篷 · 双人轻量', status: 'packed', container: 'backpack', brand: 'Big Agnes Copper Spur HV UL2', packed: true },
    { id: 'i24', cat: 'out', name: '睡袋 · 舒适 -5°C', status: 'packed', container: 'backpack', brand: 'Sea to Summit Spark III', packed: true },
    { id: 'i25', cat: 'out', name: '睡垫', status: 'must', container: 'backpack', brand: 'Therm-a-Rest NeoAir XLite', packed: false },
    { id: 'i26', cat: 'out', name: '登山杖', status: 'packed', container: 'backpack', brand: 'Black Diamond Distance Carbon', packed: true },
    { id: 'i27', cat: 'out', name: '头灯', status: 'packed', container: 'backpack', brand: 'Petzl Actik Core', packed: true },
    { id: 'i28', cat: 'out', name: '便携炉具 + 气罐', status: 'buy', container: 'backpack', note: '当地购买气罐 · 禁带上机', packed: false },

    { id: 'i29', cat: 'care', name: '洗漱套装', status: 'packed', container: 'suitcase', packed: true },
    { id: 'i30', cat: 'care', name: '防晒霜 SPF50', status: 'packed', container: 'backpack', packed: true },
    { id: 'i31', cat: 'care', name: '驱虫喷雾', status: 'must', container: 'backpack', note: '山区蚂蟥多', packed: false },
    { id: 'i32', cat: 'care', name: '快干毛巾', status: 'opt', container: 'backpack', packed: false },
    { id: 'i33', cat: 'care', name: '湿巾 × 2 包', status: 'must', container: 'backpack', packed: false },

    { id: 'i34', cat: 'tech', name: '手机 + 充电线', status: 'packed', container: 'body', packed: true },
    { id: 'i35', cat: 'tech', name: '充电宝 10000mAh', status: 'packed', container: 'backpack', packed: true },
    { id: 'i36', cat: 'tech', name: '日本插头转换器', status: 'buy', container: 'backpack', note: 'A型插头', packed: false },
    { id: 'i37', cat: 'tech', name: '相机 + 备用电池', status: 'opt', container: 'backpack', brand: 'Sony α7 IV', packed: false },

    { id: 'i38', cat: 'med', name: '个人药品', status: 'must', container: 'backpack', packed: false },
    { id: 'i39', cat: 'med', name: '创可贴 + 纱布', status: 'packed', container: 'backpack', packed: true },
    { id: 'i40', cat: 'med', name: '防水胶带', status: 'opt', container: 'backpack', note: '起泡预防', packed: false },
  ],
};
