delete from public.community_template_items where template_id in (select id from public.community_templates where slug = 'packhacker-hostel-essentials');
delete from public.community_templates where slug = 'packhacker-hostel-essentials';

insert into public.community_templates (
  slug, title, title_en, author_name, region, country, scenes, days_min, days_max, season, difficulty, description, note, is_featured, likes, copy_count, is_system
) values (
  'packhacker-hostel-essentials', 'Pack Hacker · Hostel Essentials Packing List', 'Hostel Essentials Packing List', 'Pack Hacker', 'GLOBAL', null, '{city_explore,backpacking}', null, null, null, null, '以青年旅舍入住场景为核心的轻量化清单，覆盖背包收纳、衣物、电子、洗护与杂项。', '来源：https://www.packhacker.com/packing-list/hostel-essentials-packing-list/；可按个人路线和气候调整。', false, 0, 0, true
);

with target as (
  select id from public.community_templates where slug = 'packhacker-hostel-essentials'
)
insert into public.community_template_items (
  template_id, section, name, category, status, container, brand, note, sort_order
)
values
((select id from target), 'Bags & Organizers', 'tomtoc Wander-T26 Daily Sling 5.5L', 'bags', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 1),
((select id from target), 'Bags & Organizers', 'FORCLAZ Foldable Backpack 10L', 'bags', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 2),
((select id from target), 'Bags & Organizers', 'Moment Everything Sling 1L', 'bags', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 3),
((select id from target), 'Bags & Organizers', 'Chums Surfshorts Wallet', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 4),
((select id from target), 'Clothing & Accessories', 'New Balance Premium Performance Trunks (x3)', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 5),
((select id from target), 'Clothing & Accessories', 'Saucony Performance Comfort Fit No-Show Socks (x5)', 'footwear', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 6),
((select id from target), 'Clothing & Accessories', 'Hanes Sport Cool DRI Performance T-Shirt', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 7),
((select id from target), 'Clothing & Accessories', 'Baleaf Outdoor Running Workout Short-Sleeve T-Shirt (x2)', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 8),
((select id from target), 'Clothing & Accessories', 'Baleaf Long Sleeve Shirt', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 9),
((select id from target), 'Clothing & Accessories', 'Outdoor Research Trail Mix Quarter Zip Pullover', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 10),
((select id from target), 'Clothing & Accessories', 'Outdoor Research Ferrosi Shorts', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 11),
((select id from target), 'Clothing & Accessories', 'Columbia Men’s PFG Backcast III Water Shorts', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 12),
((select id from target), 'Clothing & Accessories', 'Baleaf Lightweight Jogger Pants', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 13),
((select id from target), 'Clothing & Accessories', 'Outdoor Research Ferrosi Pants', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 14),
((select id from target), 'Clothing & Accessories', 'Columbia Men’s Rapid Rivers Pants', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 15),
((select id from target), 'Clothing & Accessories', 'FINETOO Seamless Hipster Underwear', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 16),
((select id from target), 'Clothing & Accessories', 'Parade Re:Play New Triangle Bralette (x2)', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 17),
((select id from target), 'Clothing & Accessories', 'Brooks Drive 3 Pocket Run Bra', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 18),
((select id from target), 'Clothing & Accessories', 'Saucony Performance Comfort Fit No-Show Socks (x3)', 'footwear', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 19),
((select id from target), 'Clothing & Accessories', 'prAna Everyday Tank', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 20),
((select id from target), 'Clothing & Accessories', 'Madewell Softfade Cotton Lakeshore Crop Tee', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 21),
((select id from target), 'Clothing & Accessories', 'Gap Organic Cotton Vintage Crewneck T-Shirt', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 22),
((select id from target), 'Clothing & Accessories', 'Quince Flowknit Ultra-Soft Performance Tee (x2)', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 23),
((select id from target), 'Clothing & Accessories', 'Coolibar Sanibel Everyday Beach Shawl', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 24),
((select id from target), 'Clothing & Accessories', 'Pact Airplane Wrap Cardigan', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 25),
((select id from target), 'Clothing & Accessories', 'Levi''s Women’s Mid Length Shorts', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 26),
((select id from target), 'Clothing & Accessories', 'Athleta Salutation High Rise Jogger', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 27),
((select id from target), 'Clothing & Accessories', 'Pact On the Go-To Legging', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 28),
((select id from target), 'Clothing & Accessories', 'Aerie Bathing Suit', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 29),
((select id from target), 'Clothing & Accessories', 'Quince Tencel Jersey Fit & Flare Dress', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 30),
((select id from target), 'Clothing & Accessories', 'Standard Pajamas', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 31),
((select id from target), 'Clothing & Accessories', 'Quechua Waterproof Hiking Jacket Raincut Half-Zip', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 32),
((select id from target), 'Clothing & Accessories', 'Carhartt Knit Cuffed Beanie', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 33),
((select id from target), 'Clothing & Accessories', 'Gravel Travelers Hat', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 34),
((select id from target), 'Clothing & Accessories', 'lululemon Fast and Free Running Hat', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 35),
((select id from target), 'Clothing & Accessories', 'Smartwool Liner Gloves', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 36),
((select id from target), 'Clothing & Accessories', 'Buff USA Coolnet UV+', 'clothing', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 37),
((select id from target), 'Clothing & Accessories', 'goodr A Ginger’s Soul Sunglasses', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 38),
((select id from target), 'Clothing & Accessories', 'Merrell Nova 4', 'footwear', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 39),
((select id from target), 'Clothing & Accessories', 'Havaianas Flip Flops', 'footwear', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 40),
((select id from target), 'Clothing & Accessories', 'Teva TirraTraveler Flip-Flop', 'footwear', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 41),
((select id from target), 'Clothing & Accessories', 'Vessi Cityscape', 'footwear', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 42),
((select id from target), 'Clothing & Accessories', 'Osprey Ultralight Packing Cube Set', 'bags', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 43),
((select id from target), 'Productivity & Tech', 'Amazon Kindle Paperwhite', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 44),
((select id from target), 'Productivity & Tech', 'OneAdaptr OneWorld PD', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 45),
((select id from target), 'Productivity & Tech', 'Belkin Braided USB-C to Lightning Cable', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 46),
((select id from target), 'Productivity & Tech', 'Anker PowerLine II 3-in-1 Cable', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 47),
((select id from target), 'Productivity & Tech', 'Anker 325 Power Bank (PowerCore 20K)', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 48),
((select id from target), 'Productivity & Tech', 'Apple iPhone', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 49),
((select id from target), 'Productivity & Tech', 'Standard Phone Case', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 50),
((select id from target), 'Productivity & Tech', 'Soundcore Space A40 Noise Cancelling Earbuds', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 51),
((select id from target), 'Productivity & Tech', 'Pokka Pens Classic Pen', 'documents', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 52),
((select id from target), 'Productivity & Tech', 'Rite in the Rain Top Spiral Notebook (No. 946)', 'documents', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 53),
((select id from target), 'Productivity & Tech', 'MUZEN Wild Go Bluetooth Speaker', 'electronics', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 54),
((select id from target), 'Toiletries & Personal Care', 'Osprey Ultralight Roll Organizer', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 55),
((select id from target), 'Toiletries & Personal Care', 'Kent 87T Handmade Folding Pocket Comb', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 56),
((select id from target), 'Toiletries & Personal Care', 'Gillette Sensor 3 Disposable Razor', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 57),
((select id from target), 'Toiletries & Personal Care', 'L.L.Bean Personal Organizer Toiletry Bag', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 58),
((select id from target), 'Toiletries & Personal Care', 'URTHEONE Wooden Boar Bristle Hair Brush Mini', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 59),
((select id from target), 'Toiletries & Personal Care', 'Gillette Venus Mini', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 60),
((select id from target), 'Toiletries & Personal Care', 'Crystal Mineral Deodorant Stick', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 61),
((select id from target), 'Toiletries & Personal Care', 'GUM Travel Toothbrush', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 62),
((select id from target), 'Toiletries & Personal Care', 'Standard Travel Toothpaste', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 63),
((select id from target), 'Toiletries & Personal Care', 'Milani Conceal + Perfect 2-in-1 Foundation + Concealer', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 64),
((select id from target), 'Toiletries & Personal Care', 'Milani All-Inclusive Eye, Cheek & Face Palette', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 65),
((select id from target), 'Toiletries & Personal Care', 'Maybelline Great Lash Waterproof Mascara', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 66),
((select id from target), 'Toiletries & Personal Care', 'COSHINE Portable ON THE GO Makeup Brush Set', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 67),
((select id from target), 'Toiletries & Personal Care', 'Revlon Precision Stainless Steel Tweezers', 'first_aid', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 68),
((select id from target), 'Toiletries & Personal Care', 'Tweezerman Fingernail Clipper', 'first_aid', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 69),
((select id from target), 'Toiletries & Personal Care', 'Chap-Ice Lip Naturals Mini Lip Balm (x2)', 'first_aid', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 70),
((select id from target), 'Toiletries & Personal Care', 'Matador FlatPak Toiletry Bottle (x2)', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 71),
((select id from target), 'Toiletries & Personal Care', 'Matador Ultralight Travel Towel', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 72),
((select id from target), 'Toiletries & Personal Care', 'Nomadix Ultralight Towel', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 73),
((select id from target), 'Toiletries & Personal Care', 'LastObject LastPad', 'first_aid', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 74),
((select id from target), 'Toiletries & Personal Care', 'Standard Menstrual Cup', 'first_aid', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 75),
((select id from target), 'Toiletries & Personal Care', 'Ziploc Quart Sized Bag (x2)', 'toiletries', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 76),
((select id from target), 'Miscellaneous', 'Topo Designs Accessory Bags (x2)', 'other', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 77),
((select id from target), 'Miscellaneous', 'humangear GoBites Duo', 'other', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 78),
((select id from target), 'Miscellaneous', 'Annaklin Collapsible Food Storage Containers', 'nutrition', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 79),
((select id from target), 'Miscellaneous', 'ANBOW Silicone Earplugs', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 80),
((select id from target), 'Miscellaneous', 'Hoyle Waterproof Playing Cards', 'other', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 81),
((select id from target), 'Miscellaneous', 'NITECORE TIKI 300', 'other', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 82),
((select id from target), 'Miscellaneous', 'BRINKS 30mm Solid Brass 4-Dial Resettable Padlock', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 83),
((select id from target), 'Miscellaneous', 'Matador Droplet Water-Resistant Stuff Sack', 'other', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 84),
((select id from target), 'Miscellaneous', 'Heroclip Hybrid Carabiner Clip', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 85),
((select id from target), 'Miscellaneous', 'Nite Ize S-Biner SlideLock (x3)', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 86),
((select id from target), 'Miscellaneous', 'VELCRO Brand Cable Ties (x2)', 'other', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 87),
((select id from target), 'Miscellaneous', 'Nalgene Wide-Mouth Water Bottle 32oz', 'nutrition', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 88),
((select id from target), 'Miscellaneous', 'Fiskars Travel Sewing Kit', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 89),
((select id from target), 'Miscellaneous', 'Tide To Go Instant Stain Remover', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 90),
((select id from target), 'Miscellaneous', 'MODL Outdoors Infinity Tool 2.0', 'accessories', 'must', null, null, '以青年旅舍住宿为核心，强调轻量、预算友好与多场景复用。', 91)
on conflict (template_id, name) do update set
  section = excluded.section,
  category = excluded.category,
  status = excluded.status,
  container = excluded.container,
  brand = excluded.brand,
  note = excluded.note,
  sort_order = excluded.sort_order;
