with target as (select id from public.community_templates where slug = 'packhacker-hostel-essentials')
update public.community_template_items i set image_url = v.image_url from (values
('ANBOW Silicone Earplugs', 'https://cdn.packhacker.com/2022/11/6b461180-anbow-silicone-earplugs.jpg'),
('Aerie Bathing Suit', 'https://cdn.packhacker.com/2022/12/c89d6084-aerie-bathing-suit.jpg'),
('Amazon Kindle Paperwhite', 'https://cdn.packhacker.com/2019/11/2839d979-amazon-kindle-paperwhite.jpg'),
('Anker 325 Power Bank (PowerCore 20K)', 'https://cdn.packhacker.com/2024/05/26e39296-anker-325-power-bank-powercore-20k.jpg'),
('Anker PowerLine II 3-in-1 Cable', 'https://cdn.packhacker.com/2021/03/bf0b8ba4-anker-powerline-ii-3-in-1-cable.jpg'),
('Annaklin Collapsible Food Storage Containers', 'https://cdn.packhacker.com/2022/11/66773ebf-annaklin-collapsible-food-storage-containers.jpg'),
('Athleta Salutation High Rise Jogger', 'https://cdn.packhacker.com/2025/05/0ea23142-athleta-salutation-high-rise-jogger.jpg'),
('BRINKS 30mm Solid Brass 4-Dial Resettable Padlock', 'https://cdn.packhacker.com/2024/06/57b234c5-brinks-30mm-solid-brass-4-dial-resettable-padlock.jpg'),
('Baleaf Lightweight Jogger Pants', 'https://cdn.packhacker.com/2022/11/43c7f013-baleaf-lightweight-jogger-pants.jpg'),
('Baleaf Long Sleeve Shirt', 'https://cdn.packhacker.com/2022/11/67d6336b-baleaf-long-sleeve-shirt.jpg'),
('Baleaf Outdoor Running Workout Short-Sleeve T-Shirt (x2)', 'https://cdn.packhacker.com/2022/11/7fca5a72-baleaf-outdoor-running-workout-short-sleeve-t-shirt.jpg'),
('Belkin Braided USB-C to Lightning Cable', 'https://cdn.packhacker.com/2022/11/f39c09c8-belkin-braided-usb-c-to-lightning-cable.jpg'),
('Brooks Drive 3 Pocket Run Bra', 'https://cdn.packhacker.com/2022/11/e6c1e5be-brooks-drive-3-pocket-run-bra.jpg'),
('Buff USA Coolnet UV+', 'https://cdn.packhacker.com/2021/03/00485e68-buff-usa-coolnet-uv-plus.jpg'),
('COSHINE Portable ON THE GO Makeup Brush Set', 'https://cdn.packhacker.com/2024/06/e8d0b27d-coshin-portable-on-the-go-makeup-brush-set.jpg'),
('Carhartt Knit Cuffed Beanie', 'https://cdn.packhacker.com/2022/10/67bee716-carhartt-knit-cuffed-beanie.jpg'),
('Chap-Ice Lip Naturals Mini Lip Balm (x2)', 'https://cdn.packhacker.com/2022/11/3c38e5c3-chap-ice-lip-naturals-mini-lip-balm.jpg'),
('Chums Surfshorts Wallet', 'https://cdn.packhacker.com/2022/09/8e081f6e-chums-surfshorts-wallet.jpg'),
('Columbia Men’s PFG Backcast III Water Shorts', 'https://cdn.packhacker.com/2022/11/d8cf2ef5-columbia-mens-pfg-backcast-iii-water-shorts.jpg'),
('Columbia Men’s Rapid Rivers Pants', 'https://cdn.packhacker.com/2022/11/ba014542-columbia-mens-rapid-rivers-pants.jpg'),
('Coolibar Sanibel Everyday Beach Shawl', 'https://cdn.packhacker.com/2022/11/e09a9f26-coolibar-sanibel-everyday-beach-shawl.jpg'),
('Crystal Mineral Deodorant Stick', 'https://cdn.packhacker.com/2019/04/crystal-deodorant-stick.jpg'),
('FINETOO Seamless Hipster Underwear', 'https://cdn.packhacker.com/2024/06/fa7e8d11-finetoo-seamless-hipster-underwear.jpg'),
('FORCLAZ Foldable Backpack 10L', 'https://cdn.packhacker.com/2022/12/9421f984-forclaz-100-compact-10l-travel-backpack.png'),
('Fiskars Travel Sewing Kit', 'https://cdn.packhacker.com/2022/11/1a2b7bd2-fiskars-travel-sewing-kit.jpg'),
('GUM Travel Toothbrush', 'https://cdn.packhacker.com/2021/08/3e55027e-brand-product.jpg'),
('Gap Organic Cotton Vintage Crewneck T-Shirt', 'https://cdn.packhacker.com/2024/05/f93885d9-wrangler-atg-synthetic-utility-pant.jpg'),
('Gillette Sensor 3 Disposable Razor', 'https://cdn.packhacker.com/2019/08/8cd4c21a-gillette-sensor-3-razor.jpg'),
('Gillette Venus Mini', 'https://cdn.packhacker.com/2022/01/d160c65c-gillette-venus-mini.jpg'),
('Gravel Travelers Hat', 'https://cdn.packhacker.com/2022/11/712f596a-gravel-the-travelers-hat.jpg'),
('Hanes Sport Cool DRI Performance T-Shirt', 'https://cdn.packhacker.com/2022/11/f00a3a57-hanes-sport-training-tee.jpg'),
('Havaianas Flip Flops', 'https://cdn.packhacker.com/2022/11/6ccdedf9-havaianas-flip-flops.jpg'),
('Hoyle Waterproof Playing Cards', 'https://cdn.packhacker.com/2022/11/3fe83487-hoyle-waterproof-playing-cards.jpg'),
('Kent 87T Handmade Folding Pocket Comb', 'https://cdn.packhacker.com/2022/11/c02dd1d8-kent-87t-handmade-folding-pocket-comb.jpg'),
('L.L.Bean Personal Organizer Toiletry Bag', 'https://cdn.packhacker.com/2022/11/b50d50b3-l-l-bean-personal-organizer-toiletry-bag.jpg'),
('LastObject LastPad', 'https://cdn.packhacker.com/2022/11/6e286b77-lastobject-lastpad.jpg'),
('Levi''s Women’s Mid Length Shorts', 'https://cdn.packhacker.com/2022/11/02f49b1c-levis-womens-mid-length-shorts.jpg'),
('MODL Outdoors Infinity Tool 2.0', 'https://cdn.packhacker.com/2023/07/7d5bd2df-modl-outdoors-infinity-tool-2.jpg'),
('MUZEN Wild Go Bluetooth Speaker', 'https://cdn.packhacker.com/2023/10/19ffd670-muzen-wild-go-rugged-outdoor-street-portable-bluetooth-speaker.jpg'),
('Madewell Softfade Cotton Lakeshore Crop Tee', 'https://cdn.packhacker.com/2022/11/67622abf-madewell-softfade-cotton-lakeshore-crop-tee.jpg'),
('Matador Droplet Water-Resistant Stuff Sack', 'https://cdn.packhacker.com/2022/02/b4d5112b-matador-droplet-water-resistant-stuff-sack.jpg'),
('Matador FlatPak Toiletry Bottle (x2)', 'https://cdn.packhacker.com/2019/03/matador-flatpak-toiletry-bottle.jpg'),
('Matador Ultralight Travel Towel', 'https://cdn.packhacker.com/2021/06/39bfbc49-product-hero.jpg'),
('Maybelline Great Lash Waterproof Mascara', 'https://cdn.packhacker.com/2022/11/3c2bea10-maybelline-great-lash-waterproof-mascara.jpg'),
('Merrell Nova 4', 'https://cdn.packhacker.com/2024/06/af7956e6-merrell-nova-3.jpg'),
('Milani All-Inclusive Eye, Cheek & Face Palette', 'https://cdn.packhacker.com/2022/05/d84a9e65-cheek-face-palette.jpg'),
('Milani Conceal + Perfect 2-in-1 Foundation + Concealer', 'https://cdn.packhacker.com/2022/11/34c9dd0d-milani-conceal-perfect-2-in-1-foundation-concealer.jpg'),
('Moment Everything Sling 1L', 'https://cdn.packhacker.com/2022/02/e4306939-moment-mtw-mini-fanny-sling-1l.jpg'),
('NITECORE TIKI 300', 'https://cdn.packhacker.com/2023/03/1548874a-nitecore-tiki.jpg'),
('Nalgene Wide-Mouth Water Bottle 32oz', 'https://cdn.packhacker.com/2020/05/51dd3c6f-nalgene-wide-mouth-water-bottle-32oz.jpg'),
('New Balance Premium Performance Trunks (x3)', 'https://cdn.packhacker.com/2022/11/e77711d3-new-balance-premium-performance-trunks.jpg'),
('Nite Ize S-Biner SlideLock (x3)', 'https://cdn.packhacker.com/2022/04/6c6ed9c3-nite-ize-s-biner-slidelock-aluminum.jpg'),
('Nomadix Ultralight Towel', 'https://cdn.packhacker.com/2022/05/047fb379-nomadix-ultralight-towel.jpg'),
('OneAdaptr OneWorld PD', 'https://cdn.packhacker.com/2022/10/36dbcee6-oneadaptr-oneworld-pd.jpg'),
('Osprey Ultralight Packing Cube Set', 'https://cdn.packhacker.com/2018/12/4be40a13-osprey-ultralight-packing-cube-set.jpg'),
('Osprey Ultralight Roll Organizer', 'https://cdn.packhacker.com/2022/09/9f442b85-osprey-ultralight-roll-organizer.jpg'),
('Outdoor Research Ferrosi Pants', 'https://cdn.packhacker.com/2022/05/c3056c18-outdoor-research-ferrosi-pants.jpg'),
('Outdoor Research Ferrosi Shorts', 'https://cdn.packhacker.com/2022/11/a72924dd-outdoor-research-ferrosi-shorts.jpg'),
('Outdoor Research Trail Mix Quarter Zip Pullover', 'https://cdn.packhacker.com/2022/11/2834bace-outdoor-research-trail-mix-quarter-zip-pullover.jpg'),
('Pact Airplane Wrap Cardigan', 'https://cdn.packhacker.com/2022/11/cdbdca62-pact-airplane-cardigan.jpg'),
('Pact On the Go-To Legging', 'https://cdn.packhacker.com/2024/06/e8d0b27d-coshin-portable-on-the-go-makeup-brush-set.jpg'),
('Parade Re:Play New Triangle Bralette (x2)', 'https://cdn.packhacker.com/2022/11/1ef4bd8e-parade-dream-fit-triangle-bralette.jpg'),
('Pokka Pens Classic Pen', 'https://cdn.packhacker.com/2020/08/d1e7dbd1-pokka-pens-classic-pokka-pen.jpg'),
('Quechua Waterproof Hiking Jacket Raincut Half-Zip', 'https://cdn.packhacker.com/2023/01/3c610e7f-quechua-waterproof-hiking-jacket-raincut-half-zip.jpg'),
('Quince Flowknit Ultra-Soft Performance Tee (x2)', 'https://cdn.packhacker.com/2022/11/7eebc672-matador-refillable-toothpaste-tubes.jpg'),
('Quince Tencel Jersey Fit & Flare Dress', 'https://cdn.packhacker.com/2022/11/e6beccbf-quince-tencel-jersey-fit-flare-dress.jpg'),
('Revlon Precision Stainless Steel Tweezers', 'https://cdn.packhacker.com/2022/11/b42b10d0-revlon-precision-stainless-steel-tweezers.jpg'),
('Rite in the Rain Top Spiral Notebook (No. 946)', 'https://cdn.packhacker.com/2022/10/b6a7a6ad-rite-in-the-rain-top-spiral-notebook-no-946.jpg'),
('Saucony Performance Comfort Fit No-Show Socks (x3)', 'https://cdn.packhacker.com/2019/08/ea440084-saucony-socks.jpg'),
('Saucony Performance Comfort Fit No-Show Socks (x5)', 'https://cdn.packhacker.com/2019/08/ea440084-saucony-socks.jpg'),
('Smartwool Liner Gloves', 'https://cdn.packhacker.com/2019/04/smartwool-liner-gloves.jpg'),
('Soundcore Space A40 Noise Cancelling Earbuds', 'https://cdn.packhacker.com/2022/11/ba7c91c1-soundcore-space-a40-noise-cancelling-earbuds.jpg'),
('Standard Menstrual Cup', 'https://cdn.packhacker.com/2022/12/af0a537e-menstrual-cup.jpg'),
('Standard Pajamas', 'https://cdn.packhacker.com/2022/12/0bb76d58-standard-pajamas.jpg'),
('Standard Phone Case', 'https://cdn.packhacker.com/2022/11/6d935a97-standard-phone-case.jpg'),
('Standard Travel Toothpaste', 'https://cdn.packhacker.com/2022/03/a4d12236-generic-travel-toothpaste.jpg'),
('Teva TirraTraveler Flip-Flop', 'https://cdn.packhacker.com/2025/05/1c169788-teva-tirratraveler-flip-flop.jpg'),
('Tide To Go Instant Stain Remover', 'https://cdn.packhacker.com/2020/06/efd5bf95-tide-to-go-instant-stain-remover.jpg'),
('Topo Designs Accessory Bags (x2)', 'https://cdn.packhacker.com/2019/05/251e3d26-topo-designs-accessory-bags.jpg'),
('Tweezerman Fingernail Clipper', 'https://cdn.packhacker.com/2022/02/66beb6c6-tweezerman-fingernail-clipper.jpg'),
('URTHEONE Wooden Boar Bristle Hair Brush Mini', 'https://cdn.packhacker.com/2024/06/5d4fd1fa-urtheone-wooden-boar-bristle-hair-brush-mini.jpg'),
('VELCRO Brand Cable Ties (x2)', 'https://cdn.packhacker.com/2021/08/9e24d129-brand-product.jpg'),
('Vessi Cityscape', 'https://cdn.packhacker.com/2022/08/83b43753-vessi-cityscape.jpg'),
('Ziploc Quart Sized Bag (x2)', 'https://cdn.packhacker.com/2019/02/ziploc-quart-sized-bag.jpg'),
('goodr A Ginger’s Soul Sunglasses', 'https://cdn.packhacker.com/2022/10/5de532cf-goodr-a-gingers-soul-sunglasses.jpg'),
('humangear GoBites Duo', 'https://cdn.packhacker.com/2020/10/36cdff90-humangear-gobites-duo.jpg'),
('lululemon Fast and Free Running Hat', 'https://cdn.packhacker.com/2025/05/09897518-lululemon-fast-and-free-running-hat.jpg'),
('prAna Everyday Tank', 'https://cdn.packhacker.com/2023/02/4fae2f15-prana-womens-cozy-up-tank.jpg'),
('tomtoc Wander-T26 Daily Sling 5.5L', 'https://cdn.packhacker.com/2024/02/20284741-tomtoc-wander-t26-daily-sling-5-5l.jpg')
) as v(name, image_url) where i.template_id = (select id from target) and i.name = v.name;
